#!/usr/bin/env node
// Vendor-sync — stamp the canonical `lib/*.mjs` modules into each consuming
// bundle (ADR-0004 / A-534).
//
// Bundles must stay independently installable (zero cross-bundle imports), so
// shared logic can't be a runtime import — instead this script COPIES each
// canonical `lib/` file into every consumer's `scripts/lib/vendor/` with a
// generated do-not-edit banner. CI runs `--check` to fail the build if any
// vendored copy has drifted from its canonical source.
//
//   node infrastructure/scripts/vendor-sync.mjs            # write the vendored copies
//   node infrastructure/scripts/vendor-sync.mjs --check    # fail (exit 1) on drift; write nothing
//   node infrastructure/scripts/vendor-sync.mjs --self-test # offline self-check
//   node infrastructure/scripts/vendor-sync.mjs --help      # show this message (alias: -h)
//
// Exit codes: 0 success / no drift; 1 drift detected (under --check); 2 usage error.

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

const REPO_ROOT = join(import.meta.dirname, "..", "..");

// Each canonical `lib/<file>` is vendored into one or more bundle destinations.
// Add a row here (and run `pnpm vendor:sync`) when a new shared module or
// consumer appears. Paths are repo-root-relative and use POSIX separators.
const MANIFEST = [
  {
    destinations: ["skills/changelog/scripts/lib/vendor/issue-keys.mjs"],
    source: "lib/issue-keys.mjs",
  },
  {
    destinations: [
      "skills/preflight/scripts/lib/vendor/base-branch.mjs",
      "skills/rheged-skills-setup/scripts/lib/vendor/base-branch.mjs",
    ],
    source: "lib/base-branch.mjs",
  },
];

const USAGE = `vendor-sync — copy canonical lib/*.mjs into each bundle's scripts/lib/vendor/ (ADR-0004)

Usage:
  node vendor-sync.mjs              Write the vendored copies
  node vendor-sync.mjs --check      Report drift and exit 1; write nothing
  node vendor-sync.mjs --self-test  Run the offline self-check
  node vendor-sync.mjs --help       Show this message (alias: -h)`;

/**
 * Render the exact bytes a vendored copy must contain: a generated banner
 * naming the canonical source, then that source verbatim. Keeping this pure (no
 * I/O) is what lets `--check` recompute the expected content and diff it.
 * @param {string} sourceRel  repo-root-relative path of the canonical file
 * @param {string} sourceContent
 * @returns {string}
 */
export function renderVendored(sourceRel, sourceContent) {
  const banner =
    `// @generated by \`pnpm vendor:sync\` from ${sourceRel} — DO NOT EDIT.\n` +
    `// Canonical source: ${sourceRel}. CI \`pnpm vendor:check\` fails on drift (ADR-0004).\n\n`;
  return banner + sourceContent;
}

/**
 * Flatten the manifest into one entry per destination, each carrying the exact
 * content that destination should hold.
 * @param {string} [root]
 * @returns {{ source: string, destination: string, expected: string }[]}
 */
export function computeVendorPlan(root = REPO_ROOT) {
  const plan = [];
  for (const { destinations, source } of MANIFEST) {
    const sourceContent = readFileSync(join(root, source), "utf8");
    const expected = renderVendored(source, sourceContent);
    for (const destination of destinations) {
      plan.push({ destination, expected, source });
    }
  }

  return plan;
}

/**
 * Return the destinations whose on-disk content differs from (or is missing
 * relative to) what the canonical source dictates. Empty array ⇒ in sync.
 * @param {string} [root]
 * @returns {{ destination: string, reason: "missing" | "drift" }[]}
 */
export function detectDrift(root = REPO_ROOT) {
  const drift = [];
  for (const { destination, expected } of computeVendorPlan(root)) {
    const absolute = join(root, destination);
    if (!existsSync(absolute)) {
      drift.push({ destination, reason: "missing" });
      continue;
    }

    if (readFileSync(absolute, "utf8") !== expected) {
      drift.push({ destination, reason: "drift" });
    }
  }

  return drift;
}

/**
 * Write every vendored copy from its canonical source.
 * @param {string} [root]
 * @returns {string[]} the destinations written
 */
export function writeVendored(root = REPO_ROOT) {
  const written = [];
  for (const { destination, expected } of computeVendorPlan(root)) {
    const absolute = join(root, destination);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, expected);
    written.push(destination);
  }

  return written;
}

function main(argv) {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(USAGE);
    return;
  }

  if (argv.includes("--self-test")) {
    selfTest();
    return;
  }

  if (argv.includes("--check")) {
    const drift = detectDrift();
    if (drift.length === 0) {
      console.log("vendor-sync: all vendored copies are in sync.");
      return;
    }

    console.error(
      "vendor-sync: vendored copies are out of sync — run `pnpm vendor:sync`:",
    );
    for (const { destination, reason } of drift) {
      console.error(
        `  ${reason === "missing" ? "missing" : "drifted"}: ${destination}`,
      );
    }

    process.exit(1);
  }

  const written = writeVendored();
  console.log(`vendor-sync: wrote ${written.length} vendored file(s):`);
  for (const destination of written) {
    console.log(`  ${destination}`);
  }
}

// ---- self-test ----------------------------------------------------------

function selfTest() {
  const cases = [];

  // renderVendored is pure: banner names the source and the body follows verbatim.
  const rendered = renderVendored("lib/x.mjs", "export const x = 1;\n");
  cases.push({
    name: "renderVendored prepends a banner naming the source",
    ok: rendered.startsWith("// @generated") && rendered.includes("lib/x.mjs"),
  });
  cases.push({
    name: "renderVendored preserves the source body verbatim",
    ok: rendered.endsWith("export const x = 1;\n"),
  });

  // detectDrift / writeVendored against a throwaway repo skeleton.
  const root = mkdtempSync(join(tmpdir(), "vendor-sync-"));
  try {
    mkdirSync(join(root, "lib"), { recursive: true });
    writeFileSync(join(root, "lib", "issue-keys.mjs"), "export const a = 1;\n");
    writeFileSync(
      join(root, "lib", "base-branch.mjs"),
      "export const b = 2;\n",
    );

    const before = detectDrift(root);
    cases.push({
      name: "detectDrift flags every destination as missing before a sync",
      ok:
        before.length === 3 &&
        before.every((entry) => entry.reason === "missing"),
    });

    writeVendored(root);
    cases.push({
      name: "detectDrift is empty immediately after writeVendored",
      ok: detectDrift(root).length === 0,
    });

    // A hand-edit to a vendored copy is caught as drift.
    writeFileSync(
      join(root, "skills/changelog/scripts/lib/vendor/issue-keys.mjs"),
      "tampered\n",
    );
    const after = detectDrift(root);
    cases.push({
      name: "detectDrift catches a hand-edited vendored copy",
      ok:
        after.length === 1 &&
        after[0].reason === "drift" &&
        after[0].destination.endsWith(
          "changelog/scripts/lib/vendor/issue-keys.mjs",
        ),
    });
  } finally {
    rmSync(root, { force: true, recursive: true });
  }

  let failed = 0;
  for (const { name, ok } of cases) {
    console.log(`  ${ok ? "ok  " : "FAIL"}  ${name}`);
    if (!ok) {
      failed += 1;
    }
  }

  console.log(`\n${cases.length - failed}/${cases.length} passed`);
  process.exit(failed === 0 ? 0 : 1);
}

// Only run when invoked directly as a CLI, not when imported (e.g. by the vitest
// suite). Compare realpath'd paths so symlinks (macOS /var→/private/var) don't
// cause a false negative.
function isCliEntry() {
  if (!process.argv[1]) {
    return false;
  }

  try {
    return realpathSync(import.meta.filename) === realpathSync(process.argv[1]);
  } catch {
    return false;
  }
}

if (isCliEntry()) {
  main(process.argv.slice(2));
}
